---
---

## Flow Control

The syntax for "if ... then" tests and for-loops involves plain
English and few special characters---you will easily ingest
it. Whitespace actually serves as the most important special
character, although you may not think of it that way, and that is our
main motivation for looking at flow control.

===

## For-loops

A `for` loop takes any "iterable" object and executes a block of code
once for each element `in` the object.

```{python handout = 0}
squares = []
for i in range(1, 5):
    j = i ** 2
    squares.append(j)
len(squares)
```

The `range(i, j)` function creates an object that iterates from `i` up
through `j - 1`; just like in the case of list slices, the range is
not inclusive of the upper bound.
{:.notes}

===

## Indentation

Note the pattern of the block above:

- the `for x in y` expression is followed by a `:`
- the following lines are indented **equally**
- un-indenting indicates the end of the block

Compared with other programming languages in which code indentation
only serves to enhance readability, Python uses indentation to define
"code blocks". In a sense, indentation serves two purposes in Python,
enhancing readiblity and defining complete statements, which is kinda
how we use indentation too.
{:.notes}

===

## Nesting Indentation

Each level of indentation indicates blocks within blocks. Nesting a
conditional within a for-loop is a common case.

The following example creates a contact list (as a list of
dictionaries), then performs a loop over all contacts. Within the
loop, a conditional statement (`if`) checks if the name is 'Alice'. If
so, the interpreter prints her email address; otherwise it prints an
empty string.
{:.notes}

```{python handout = 0}
users = [
    {'Name':'Alice', 'Email':'alice@email.com'},
    {'Name':'Bob', 'Email': 'bob@email.com'},
    ]
for u in users:
    if u['Name'] == 'Alice':
        print(u['Email'])
    else:
        print('')
```
